;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	autopair-insert-opening
	autopair-newline
	autopair-skip-close-maybe
	c-electric-delete-forward
	c-indent-line-or-region
	indent-for-tab-command
	kill-region
	undefined
	))

(setq mc/cmds-to-run-once
      '(
	kmacro-edit-macro
	write-file
	))
