#!/bin/sh
#Put this in ~/.config/
. ~/.shrc

export DMENUOPT="-b -fn 'Inconsolata-10' -fn 'Symbola'  -sf green -sb black -nb #000000 -nf green -l 3 -i"
export DMENU="dmenu $DMENUOPT"
export DOPTS='-fn "Inconsolata-10" -sf green -sb black -nb black -nf green -i'
