#! /bin/sh

# Initial programs to run

# X settings
xset -dpms
xset -b
# keybinds
systemctl --user start sxhkd.service

# Notifications
dunst &

# Audio
pulseaudio -D

# Graphics
compton &
$HOME/.config/polybar/launch.sh
xrdb -merge $HOME/.Xresources
feh --randomize --bg-scale ~/.wallpaper/*

# Daemons
urxvtd &
$HOME/bin/notify-listener.py &

# bspwm setup
bspc monitor HDMI-0 -d I
bspc monitor DVI-I-1 -d II

bspc config border_width         2
bspc config window_gap          12

bspc config pointer_follows_focus true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a mpv state=floating
bspc rule -a feh state=floating
bspc rule -a Xdialog state=floating
