(setq standard-ident 2)
(setq scroll-step 1)
(line-number-mode 1)
(column-number-mode 1)
(global-display-line-numbers-mode)
(setq-default fill-column 80)
(setq auto-fill-mode 1)
(global-set-key (kbd "C-c h") 'global-hl-line-mode)
(setq auto-mode-alist (append '(("/tmp/mutt.*" . mail-mode)) auto-mode-alist))
(setq create-lockfiles nil)
(setq backup-directory-alist `((".*" . ,(concat user-emacs-directory "backups"))))
